#!/bin/sh

DEVSETTING_DIR=$HOME/.devsetting

systemMessage=""

## Check current environments #################################################
supportNVIM=0
case "$(uname -s)" in
    Linux*)     machine=Linux; supportNVIM=1;;
    Darwin*)    machine=Mac; supportNVIM=1;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:$(uname -s)"
esac

dist="Unsupported"
if [ "$machine" = "Linux" ]; then
    case "$(cat /etc/issue)" in
        *Ubuntu*)   dist=Ubuntu;;
        *SUSE*)     dist=SUSE;;
        *)          dist="Unsupported"
    esac
fi
# TODO: check distribution of linux

## Download external libraries ################################################
# NeoVim - https://github.com/neovim/neovim/wiki/Installing-Neovim
# TODO: check nvim version
#if [ $supportNVIM = 1 ] && [ -z "$(command -v nvim)" ]; then
if [ $supportNVIM = 0 ] && [ -z "$(command -v nvim)" ]; then
    if [ "$dist" = "SUSE" ]; then
        cd $DEVSETTING_DIR/bin
        wget https://github.com/neovim/neovim/releases/download/v0.3.4/nvim.appimage --no-check-certificate
        chmod +x nvim.appimage
        mv nvim.appimage nvim
    elif [ "$dist" = "Ubuntu" ]; then
        echo "Please run \"sudo apt-get install nvim\""
    elif [ "$dist" = "Unsupported" ]; then
        echo "this distribution doesn't support nvim"
    fi
fi

[ ! -d "$DEVSETTING_DIR/git/tmux" ] &&
    git clone https://github.com/tmux/tmux.git $DEVSETTING_DIR/git/tmux
[ ! -d "$DEVSETTING_DIR/git/uctag" ] &&
    git clone https://github.com/universal-ctags/ctags.git $DEVSETTING_DIR/git/uctag
[ ! -d "$DEVSETTING_DIR/git/ag" ] &&
    git clone https://github.com/ggreer/the_silver_searcher.git $DEVSETTING_DIR/git/ag
