#!/bin/sh

DEVSETTING_DIR=$HOME/.devsetting

## Check current environments #################################################
supportNVIM=0
case "$(uname -s)" in
    Linux*)     machine=Linux; supportNVIM=1;;
    Darwin*)    machine=Mac; supportNVIM=1;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:$(uname -s)"
esac

dist="Unsupported"
if [ "$machine" = "Linux" ]; then
    case "$(cat /etc/issue)" in
        *Ubuntu*)   dist=Ubuntu;;
        *SUSE*)     dist=SUSE;;
        *)          dist="Unsupported"
    esac
fi

# NeoVim - https://github.com/neovim/neovim/wiki/Installing-Neovim
if [ $supportNVIM = 1 ] && [ -z "$(command -v nvim)" ]; then
    if [ "$dist" = "SUSE" ]; then
        cd $DEVSETTING_DIR/bin
        wget https://github.com/neovim/neovim/releases/download/v0.3.4/nvim.appimage --no-check-certificate
        chmod +x nvim.appimage
        mv nvim.appimage nvim
    elif [ "$dist" = "Ubuntu" ]; then
        echo "Please run \"sudo apt-get install nvim\""
    elif [ "$dist" = "Unsupported" ]; then
        echo "this distribution doesn't support nvim - $dist"
    fi
fi

## Install prerequiste library - need root access #############################
if [ "$dist" = "SUSE" ]; then
    echo "SUSE"
    sudo zypper install --type pattern Basis-Devel
    sudo zypper install libevent-devel ncurses-devel        # for tmux
    sudo zypper install pcre-devel zlib-devel xz-devel      # for ag
    sudo zypper install readline-devel                      # for cgdb
elif [ "$dist" = "Ubuntu" ]; then
    echo "Ubuntu"
    sudo apt-get install -y build-essential
    sudo apt-get install -y autotools-dev automake libevent-dev libncurses-dev pkg-config   # for tmux
    sudo apt-get install -y automake pkg-config libpcre3-dev zlib1g-dev liblzma-dev         # for ag
fi

## Download / Install external libraries ######################################
# TODO: should be implemented with 2d array ....
LIBS=(  "ag|https://github.com/ggreer/the_silver_searcher.git"
        "cgdb|git://github.com/cgdb/cgdb.git"
        "lynx|https://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.9rel.1.tar.gz"
        "tig|https://github.com/jonas/tig.git"
        "tmux|https://github.com/tmux/tmux.git"
        "uctags|https://github.com/universal-ctags/ctags.git"
     )

for lib in "${LIBS[@]}" ; do
    KEY="${lib%%|*}"
    VALUE="${lib##*|}"

    if [ ! -d "$DEVSETTING_DIR/git/$KEY" ]; then
        case "$VALUE" in
            *tar.gz)
                wget $VALUE -P $DEVSETTING_DIR/git
                fileName=${VALUE##*/}
                tar zxvf $DEVSETTING_DIR/git/$fileName -C $DEVSETTING_DIR/git
                rm $DEVSETTING_DIR/git/$fileName
                mv $DEVSETTING_DIR/git/${fileName%.tar.gz} $DEVSETTING_DIR/git/$KEY
                ;;
            *.git)
                git clone $VALUE $DEVSETTING_DIR/git/$KEY
                ;;
            *github*)
                git clone $VALUE $DEVSETTING_DIR/git/$KEY
                ;;
            *)
                echo "Unable to download library"
                echo "Lib: $KEY / Address: $VALUE"
                ;;
        esac
    fi
done

#if [ ! "$dist" = "SUSE" ] || [ ! "$dist" = "Ubuntu" ]; then
#    echo "this is not suse"
#fi
